seed: 42
lr: .00005
bert: bert-base-multilingual-cased
hidden: 400
p_drop: .3
dataset: ../data/hu_szeged-ud
device: cuda
grad_clip: 1.
num_warmup_steps: 20
batch_size: 20
epochs: 50
project: hu
entity: unn
unn_iter: 1
finetune_bert: True
